### PR TITLE
Add quality option

### PR DESCRIPTION
**Pull request by nischu7**

### CODE REVIEW

**Comment by codingjoe** [comment]
@nischu7 I'm not so sure about this feature, because it does only apply to JPEG.

**Comment by nischu7** [comment]
How about adding a custom kwargs option for each variation instead?

**Comment by codingjoe** [comment]
Sure, surprise me. But There will be an option do render your own variations in version 2 that I'm currently working on.

**Comment by codingjoe** [comment]
You'll find the new feature I was talking about in the async branch. I decided not to merge this patch because it doesn't apply to all file types, not is it filetype save. I might be down for a way where you can add type specific kwargs.

**Pull request closed without merging**
